version: '2'

tasks:
  release:
    cmds:
      - heroku container:push web
      - heroku container:release web
      - osascript -e 'display notification "Deploy Done" with title "Heroku Deploy" subtitle "My Go Server" sound name "Submarine"'